version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: amrutam_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amrutam_telemedicine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d amrutam_telemedicine"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: amrutam_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: amrutam_api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amrutam_telemedicine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkeychangeinproduction1234567890
      - FIELD_ENCRYPTION_KEY=3kS2yE0vP4uH9gD5xJ8zM2aQ1wR4tY7uI9oP8aS1dF0=
    ports:
      - "8005:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: amrutam_worker
    command: arq src.app.worker.worker.WorkerSettings
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amrutam_telemedicine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=supersecretkeychangeinproduction1234567890
      - FIELD_ENCRYPTION_KEY=3kS2yE0vP4uH9gD5xJ8zM2aQ1wR4tY7uI9oP8aS1dF0=
    depends_on:
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: amrutam_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

volumes:
  postgres_data:
